### ISSUE TITLE
OpenID Connect

### ISSUE THREAD

**Issue by lsmag** [idan/oauthlib#238]
Hello,

I've been reading the [OpenID Connect spec](http://openid.net/specs/openid-connect-core-1_0.html) to implement it on top of [Django-OAuth-Toolkit](https://github.com/evonove/django-oauth-toolkit/issues/110#issuecomment-36942476), but I think this feature belongs to oauthlib, what do you think?

I have some code (inside DOT, not oauthlib) which defines a new server and grant_types needed to succesfully process an OIDC Authorization Request. If you agree, I'll move that to my fork of oauthlib and write proper tests covering the spec.

**Comment by corentone** [comment]
I would like to help too!
I might fork and try to start myself unless you can share a headstart :)

**Comment by fgaudin** [comment]
I'm interested as well, any news on the subject?

**Comment by juanifioren** [comment]
@ryanhiebert @fgaudin Because of needs I start a new project, an OIDC implementation for the Django Frameworks. If someone is interested.
https://github.com/juanifioren/django-oidc-provider

**Comment by skion** [comment]
If anyone's interested, I've [rebased](https://github.com/skion/oauthlib/tree/openid_connect) the original `openid_connect` branch to master some time ago, and did some small modifications (some from this thread) to make it work for my case. It [applies cleanly](https://github.com/idan/oauthlib/compare/master...skion:openid_connect) to 0.7.2 at the moment (was 0.6.x before rebase), but is definitely not ready for merging to master. I'd be willing to help get it in a better state, though also don't feel confidently acquainted with oauthlib's innards.

**Comment by bjmc** [comment]
Has there been any more progress on this issue? I'm looking to implement an OAuth2 provider + OpenIDConnect support.

**Comment by bjmc** [comment]
@ib-lundgren 

I'm really interested in having this feature available. I've [rebased the existing openid_connect branch](https://github.com/idan/oauthlib/compare/master...bjmc:openid_connect?expand=1) onto the current master. What else do you think is needed to move this issue to completion? I'm happy to make further changes and put together a pull request if somebody is willing to review it.

**Comment by bjmc** [comment]
Sorry to sound like a broken record here, but is there any interest in getting this feature completed/merged? I don't want to put time against it unless there's interest upstream.

**Comment by rawon** [comment]
@bjmc I'm very interested. Thanks for your work.

**Comment by ntcong** [comment]
any update on this? since there's no reply from the team, should we consider this feature is not interested ?

**Comment by bjmc** [comment]
I'm not sure if this project is actively maintained or not. Would people be interested in a fork, with a more limited scope? (say, only OAuth2 + OIDC, and only server-side implementation, no client)

**Comment by clintonb** [comment]
Note that there is also an issue tracking this in a consuming project: evonove/django-oauth-toolkit#110. However, no progress has been made there, either.

**Comment by bjmc** [comment]
We need this feature for a project I'm working on. If there's no movement on this by February, I will probably be forking and merging on my fork--but I would prefer not to maintain a long running fork--and I hope that upstream maintainers will take an interest in this feature. @ib-lundgren

**Comment by clintonb** [comment]
@bjmc @ib-lundgren @idan we at edX are very interested in seeing this feature merged and supported in django-oauth-toolkit. What do you need from us to make that happen?

**Comment by fgaudin** [comment]
Now I'm using https://github.com/juanifioren/django-oidc-provider which is working well enough for our needs.

**Comment by clintonb** [comment]
@ib-lundgren @idan we at edX are very interested in seeing this feature merged and supported in django-oauth-toolkit. What do you need from us to make that happen?

**Comment by bjmc** [comment]
@clintonb At [Globus](https://www.globus.org/) we are discussing the possibility of forking oauthlib to get this feature merged. Would you or other edX devs be interested in sharing the work of maintaining a fork until such time as upstream maintainers want to incorporate our changes?

**Comment by clintonb** [comment]
@bjmc We are interested; but, I want to get some assurances from @ib-lundgren @idan that the fork will be merged. We already have a fork of the now-dead django-oauth2-provider that we want to get rid of.

**Comment by joelstevenson** [comment]
@clintonb, @bjmc, and @idan I've done some work to get the `openid_connect` branch updated and submitted a PR https://github.com/idan/oauthlib/pull/416 in the hopes that the code might eventually get there.  This may only serve as a straw-man to see what else needs to happen to get the code eventually merged but, as it is all the tests pass and I'm using Authorization Code flow in a Django app (via `django-oauth2-toolkit` updated to integrate with this version of `oauthlib`), FWIW.

**Comment by bjmc** [comment]
Thanks @joelstevenson! I made some comments on the pull request. Let's see if we can get this in a state we're happy with and get it merged.

**Comment by joelstevenson** [comment]
Great, thanks much!  I'll be continuing to work on this tomorrow and Friday, I don't want to lose any momentum although today I was stuck dealing with other things.

**Comment by thedrow** [comment]
This is fixed with #416
