### ISSUE TITLE
Not able to use ! is token request query

### ISSUE THREAD

**Issue by artooro** [idan/oauthlib#304]
See my question on stackoverflow.

My query to @oauth.token_handler contains the ! in the query string which resulted in a decoding error.

I modified oauthlib/common.py line 110 from:
urlencoded = set(always_safe) | set('=&;%+~,*@!)

to:
urlencoded = set(always_safe) | set('=&;%+~,*@!')

And that resolved the problem. I don't know if this is what I should have done, but it works. Can this fix be merged or should it be resolved some other way?

**Comment by thedrow** [comment]
This was fixed in #305.
