### ISSUE TITLE
How to set request.client.client_id for: authenticate_client(self, request, *args, **kwargs)

### ISSUE THREAD

**Issue by sabzo** [idan/oauthlib#319]
I'm implementing the Client Credentials Grant workflow (https://oauthlib.readthedocs.org/en/latest/oauth2/grants/credentials.html)  and I'm having errors in my Request Validator (https://oauthlib.readthedocs.org/en/latest/oauth2/validator.html?highlight=authenticate_client#oauthlib.oauth2.RequestValidator.authenticate_client)

This is my question: How do I set " request.client.client_id" ?  It's needed in the `authenticate_client` method, I tried to do something like:

self.server.create_token_response(req.uri, req.method, req.body, req.headers, credentials) but still no luck, please someone help.

**Comment by sabzo** [comment]
Inside  my_request_validator.authenticate_client(...) if I set request.client.client_id I get "'NoneType' object has no attribute 'client_id'".

If I don't set anything I get: "client must set the request.client.client_id attribute"?  

Otherwise I get raise NotImplementedError('Authenticate client must set the '
NotImplementedError: Authenticate client must set the request.client.client_id attribute in authenticate_client.

**Comment by sabzo** [comment]
Nvm. Had to create a Client class with a client_id attribute.

**Comment by allsyed** [comment]
`from oauthlib.oauth2 import Client`

and in, authenticate_client. set client.

`request.client = Client(request.client_id)`
