### ISSUE TITLE
Bunch of open PRs -- do you need maintainers?

### ISSUE THREAD

**Issue by tilgovi** [idan/oauthlib#333]
I see there's lots of open PRs and issues but not a ton of recent activity. Would you like help?

**Comment by ib-lundgren** [comment]
A thousand times yes. Been meaning to send out a plea for this but yet to get around to it. Last few months have been and continue to be super busy.

I'm sure there are a bunch of able hands out there and several of these are probably waiting in the PR queue already. Lets try and get through this together, I will merge any PR that has 1 or more "Looks good to me" comments on it. Please ping this bug when a PR has been reviewed and I'll make sure I take a look within the next working day :)

When the bug queue has been cleared I'll add write access to people who are interested.

**Comment by tilgovi** [comment]
You prefer I ping this issue as well as writing LGTM to on the PRs? Or should we just close this?

**Comment by ib-lundgren** [comment]
Please do either both or simply ping this bug saying along the lines of "PR #X LGTM".

Lets keep this open until the queue is cleared :)

**Comment by georgewhewell** [comment]
Can #310 be merged? Would be good to have tests passing at current version before more changes are applied.

**Comment by lepture** [comment]
ping @ib-lundgren

**Comment by ib-lundgren** [comment]
Quickly skimmed a few PRs now and will try and dig a bit deeper if time allows tomorrow :)

Keep up the great work guys and if there is something controversial / blocking / should be prioritized don't hesitate to point it out

**Comment by josephtate** [comment]
I'd be happy to pitch in as a part time maintainer. I've got #322 cleaned up and reviewed by the JWT owner, and #323 is good to go now too.

**Comment by ib-lundgren** [comment]
@josephtate that is great news :) I'd love to have a few maintainers helping out as much as they have time for.

**Comment by josephtate** [comment]
@ib-lundgren There are a bunch of issues and pull requests that can be closed now because #323 has been merged: #296, #315, #297, #307 are all duplicate/redundant.

#338 is trivial and should be accepted,
#339 includes a test and LGTM
#332 has a LGTM

**Comment by samjacoby** [comment]
Thanks, @josephtate. Here's my vote for #339. Would love to see these come on in.

**Comment by ib-lundgren** [comment]
Thanks a lot guys :)

**Comment by thedrow** [comment]
I'm willing to help maintain this library if required.

**Comment by foxx** [comment]
All the following are good for merge, they are indentation fixes in docs;

#343, #347, #349

**Comment by ib-lundgren** [comment]
I'm excited to announce that the contributor bit is now flipped for @masci, @lepture, @tilgovi, @georgewhewell, @samjacoby, @foxx, @thedrow :) Thanks for all your contributions so far and I'm looking forward to see where you help steer oauthlib from here!

I think one thing we should look at doing soon is a new PyPI release (#346). Anyone fancy writing up a change list? I'll push once we have one. 

As always, if you have a question, would like to discuss something or simply draw my attention somewhere feel free email/hangouts msg me at ib.lundgren@gmail.com. 

p.s. If you would like to become a contributor please get in touch. In this round I included people from this thread but there are many more who have made great contributions in the past. If you are one of those please do not be offended but rather sent me an email :)

**Comment by thedrow** [comment]
@ib-lundgren Can you please set up travis to release to PyPi on tag?
I'll have a changelog by sunday.

**Comment by thedrow** [comment]
I merged some of the pending PRs.
@ib-lundgren If I merged something I shouldn't have please let me know and I'll revert.

**Comment by thedrow** [comment]
Please take look at #357 and let me know if I missed something.
