### ISSUE TITLE
getattr broken on common.Request

### ISSUE THREAD

**Issue by kdazzle** [idan/oauthlib#340]
If I call `getattr(request, 'foo', {})`, `None` is returned instead of an empty dictionary.

This is because the `__getattr__` magic method is supposed to raise an AttributeError if the given attribute isn't found in the object ([see here](https://docs.python.org/2/reference/datamodel.html#object.__getattr__)), whereas right now it always returns `None`. 

This is undesirable because it breaks the expected functionality of `getattr` and could cause unexpected bugs.

**Comment by thedrow** [comment]
This is now fixed by #340.
