### ISSUE TITLE
New pypi version

### ISSUE THREAD

**Issue by marazt** [idan/oauthlib#346]
Hi, it is possible to publish new version into pypi?

**Comment by thedrow** [comment]
Now that we have cryptography instead of pycrypto we really need a new release.

**Comment by KarelJakubec** [comment]
+1

We would really appreciate a release with https://github.com/idan/oauthlib/pull/323, current situation breaks our setup a bit, as we need to clone repo first and then install it from source instead of simple 'pip install oautlib'.

Thanks

**Comment by masci** [comment]
:+1: please let me know if I can help in any way

**Comment by thedrow** [comment]
@ib-lundgren Can you please add me as a maintainer and give me access to PyPi?
I'll release it myself.

**Comment by widnyana** [comment]
@KarelJakubec since @ib-lundgren looks quite busy, you can use pip to install oauthlib from specific commit hash until he publish a new release to pypi :)

**Comment by thedrow** [comment]
New release comming soon. :)

**Comment by marazt** [comment]
:+1:

**Comment by thedrow** [comment]
I haven't forgot about this. I just didn't have the time to complete all release notes.
I'll probably release this weekend.

**Comment by mfc-julius** [comment]
+1

**Comment by thedrow** [comment]
I tried to release but something's wrong with Travis-CI. See https://github.com/travis-ci/travis-ci/issues/4464

**Comment by thedrow** [comment]
@ib-lundgren The password you provided for Travis is incorrect. https://travis-ci.org/idan/oauthlib/jobs/71644209#L422

**Comment by ib-lundgren** [comment]
@thedrow apologies. I must have mistyped it when setting up travis (yay enter-once password prompts).

I've manually pushed the new release now :) Thanks for making it happen!
