### ISSUE TITLE
setup.py install_requires list is empty

### ISSUE THREAD

**Issue by lzulauf** [idan/oauthlib#383]
While dependencies are listed in requirements.txt, they are missing from the install_requires list in setup.py. This prevents pip from automatically installing dependencies.

See pip documentation for install_requires here:
https://packaging.python.org/en/latest/requirements.html#install-requires-vs-requirements-files

It looks like at the least, install_requires should contain ['pyjwt', 'cryptography']

pip install oauthlib does not provide a working copy of oauthlib until the user either manually executes the requirements.txt file or manually installs pyjwt and cryptography.

**Comment by lepture** [comment]
Those dependencies are optional, they are in the `extra_requires`.

**Comment by alexforever86** [comment]
Getting the following error while installing:

`pkg_resources.DistributionNotFound: The 'cryptography; extra == "signedtoken"' distribution was not found and is required by oauthlib`
