### ISSUE TITLE
Which is Secure for Web Api OAuth 1 or OAuth 2

### ISSUE THREAD

**Issue by prasteli2015** [idan/oauthlib#397]
We are working to build a web api in a .net framework. So which is more secure between OAuth 1 or OAuth 2 for authentication and authorization, Kindly suggest

**Comment by bjmc** [comment]
Both are secure if implemented correctly. 

OAuth2 doesn't specify its own encryption and instead relies on SSL security over HTTPS to protect authorization codes and tokens from interception. From that perspective, you could say that OAuth1 is "more secure", but OAuth 2 is secure as long as you are careful to always require SSL connections.

If for some reason your application is unable to use HTTPS, you will need to use OAuth 1. However, OAuth 1 is significantly more complicated to implement, and the general trend in the industry seems to be toward OAuth 2.

My suggestion is to use OAuth 2 unless you have a strict requirement to support unsecured HTTP connections.

**Comment by thedrow** [comment]
Is there anything specific to oauthlib you wanted to ask?
Feel free to reopen if you did.
