### ISSUE TITLE
Query strings should be able to include forward slashes `/`

### ISSUE THREAD

**Issue by rhaining** [idan/oauthlib#404]
Per RFC 3986 section 3.4, query strings should be allowed to include forward slashes `/` & `?`.
http://tools.ietf.org/html/rfc3986#section-3.4

>  The query component is indicated by the first question
>   mark ("?") character and terminated by a number sign ("#") character
>   or by the end of the URI.

> The characters slash ("/") and question mark ("?") may represent data
>   within the query component.

Can we update https://github.com/idan/oauthlib/blob/master/oauthlib/common.py#L112 to include these characters?

Otherwise, oauthlib throws the error ala:
> Error trying to decode a non urlencoded string.

https://github.com/idan/oauthlib/blob/master/oauthlib/common.py#L131

thanks!

**Comment by Bramas** [comment]
I totally agree with this.

**Comment by macrojames** [comment]
I also read colons are allowed. I have issues with this at the moment, because some libs won't encode the redirect uris

**Comment by rhaining** [comment]
@thedrow awesome! thanks so much for fixing this.
