### ISSUE TITLE
New release on pypi ?

### ISSUE THREAD

**Issue by julienmeyer** [idan/oauthlib#408]
Hello,
Do you know when you will create the next release and push it on pypi ?
Thanks,
Julien

**Comment by eofs** [comment]
:+1:

**Comment by LennyLip** [comment]
+1

**Comment by thedrow** [comment]
Sorry. Been busy.
I will try to get to it this weekend.

**Comment by thedrow** [comment]
I'm fixing the build before the release. Please hold on.

**Comment by thedrow** [comment]
Build is fixed. Changelog is the only thing that's left.
Will do soon. Promise :)

**Comment by thedrow** [comment]
Release should hit PyPi soon. Let me know if there are any problems.
