### ISSUE TITLE
1.1.0 advertised on PyPi, but no distribution appears to be available

### ISSUE THREAD

**Issue by ViktorAtD2L** [idan/oauthlib#412]
1.1.0 seems to be listed as available on PyPi, but with no associated distribution available.

If this is just a timing issue with uploading the package, I apologize for adding an issue that's effectively noise.

**Comment by eofs** [comment]
I've the same problem, the distribution for 1.1.0 is not available:

`DistributionNotFound: No distributions matching the version for oauthlib==1.1.0`

#408

**Comment by Starefossen** [comment]
@idan @hedrow anything I, or the community, can do to help with the publishing to PyPi?

**Comment by Starefossen** [comment]
@idan @thedrow are there anything I, or the community, can do to help with to get the lastes version published to PyPi?

**Comment by thedrow** [comment]
Travis must have failed to push the package. I'll retry and do it manually if it fails again.

**Comment by thedrow** [comment]
I'm getting HTTPError: 400 Client Error: This filename has previously been used, you should use a different version. when I try to upload the release both manually and in travis.
Any idea what is this all about?

**Comment by thedrow** [comment]
Ok done. I had to rename the source distribution for some reason.
@ViktorAtD2L @eofs @Starefossen Next time ping me directly with @thedrow on such issues or catch me on twitter or something.
I hope not to disregard these kind of problems in the future.

**Comment by r4fek** [comment]
@thedrow now it doesn't play well with Devpi.. Advertised version is 1.1.0, but package is called 1.1.0-1. Devpi is unable to install 1.1.0 then (it sees only 1.1.0-1). Maybe you could bump release version and upload it this time correctly?

**Comment by ViktorAtD2L** [comment]
I believe that this is a security feature of PyPi: once a distribution is created, you can't alter its contents, so that no two package versions have the same name. However, I understood that if you registered a new package version without providing files, you could then manually attach files to the version: I may be incorrect in believing that.

**Comment by thedrow** [comment]
@r4fek I'll re-release tomorrow.

**Comment by r4fek** [comment]
Awesome!

**Comment by thedrow** [comment]
Done.
Please let me know if you find any problems.

**Comment by thedrow** [comment]
I just tested it and it's installed and upgraded just fine.
