### ISSUE TITLE
oauthlib 1.1.0.post1 

### ISSUE THREAD

**Issue by papachoco** [idan/oauthlib#418]
Currently in pypi the latest version of the library is oauthlib 1.1.0.post1.. could we make an sdist oauthlib-1.1.0.post1.tar.gz also available so legacy installations can find the correct egg

Thanks 

Carlos
ps. the egg listed in pypi is oauthlib-1.1.0-1.tar.gz

**Comment by jsingle** [comment]
+1, the inconsistency here is causing issues for me as well

**Comment by thedrow** [comment]
Could you please install 1.1.1 instead?
