### ISSUE TITLE
Programmatically add safe characters to oauthlibs urlencoded set?

### ISSUE THREAD

**Issue by BillBrower** [idan/oauthlib#419]
I want to add brackets ([, ]), and colons (:) to the urlencoded set on line 131 of common.py so that my api works with JSON API filters. Is there anyway to do that programmatically so that my api will work if I upgrade oauthlib?

Thank you,
Bill

**Comment by thedrow** [comment]
I don't think there is except setting the url safe regex to something else.

**Comment by BillBrower** [comment]
If I created a pull request for this would y'all accept it? Or is there a compelling reason to leave brackets and colons out of the standard safe character set?

**Comment by thedrow** [comment]
I might accept, depending on the design decisions made in that PR.
