### ISSUE TITLE
Drop Python 2.6 and Python 3.3

### ISSUE THREAD

**Issue by adamn** [idan/oauthlib#432]
It seems like you can safely drop 2.6 and 3.3 from the tests:

[Google's client dropped them](https://github.com/google/oauth2client/commit/49d565d2deb47bfc51416654c33dbc391b8c06e9)

[Django dropped them](https://docs.djangoproject.com/en/1.10/faq/install/#what-python-version-can-i-use-with-django)

**Comment by thedrow** [comment]
What about flask and other frameworks?

**Comment by adamn** [comment]
Flask and all currently maintained frameworks support 2.7 and 3.4+ so there's no problem there.

**Comment by adamn** [comment]
Sorry, didn't understand your statement.  Flask [does still test 2.6 and 3.3](https://github.com/pallets/flask/blob/master/tox.ini) but it really seems unnecessary unless somebody reading this is actually using one of those versions in production and planning on installing new versions of `oauthlib`.  Please comment if that's the case.
