### ISSUE TITLE
requests.scope is not allowed to be empty

### ISSUE THREAD

**Issue by crashekar** [idan/oauthlib#446]
`if not request.scopes:
                raise ValueError('Scopes must be set on post auth.')`

When the RFC mentions that scope can be empty why should this check be in place ?

**Comment by thedrow** [comment]
Can you point to the offending line of code?

**Comment by thedrow** [comment]
See comment here https://github.com/idan/oauthlib/pull/391#issuecomment-172170714

**Comment by crashekar** [comment]
Yes that is the one.

**Comment by thedrow** [comment]
@crashekar I think it's not a bug. The scope cannot be empty.
