### ISSUE TITLE
request.scopes is always None.

### ISSUE THREAD

**Issue by seyriz** [idan/oauthlib#447]
Error Info : TypeError
I using Flask-Oauthlib.Oauth2Provider for Oauth2 server.
the request.scope in ` oauthlib.oauth2.rfc6749
.AuthorizationEndpoint.validate_authorization_request()`  IS ALWAYS None.
that  `if "openid" in request.scopes:` line in ` oauthlib.oauth2.rfc6749.grant_types.openid_connect.AuthCodeGrantDispatcher._handler_for_request()` raise TypeError: argument of type 'NoneType' is not iterable. 
to avoid this error, 
 fix `oauthlib.oauth2.rfc6749.grant_types.openid_connect.AuthCodeGrantDispatcher._handler_for_request() `
``` python
    def _handler_for_request(self, request):
        handler = self.default_auth_grant

        if and "openid" in request.scopes:
            handler = self.oidc_auth_grant

        log.debug('Selecting handler for request %r.', handler)
        return handler
```

to
``` python
    def _handler_for_request(self, request):
        handler = self.default_auth_grant

        if request.scopes is not None and "openid" in request.scopes:
            handler = self.oidc_auth_grant

        log.debug('Selecting handler for request %r.', handler)
        return handler
```

**Comment by thedrow** [comment]
Try the new version.
