### ISSUE TITLE
Support on microsoft online

### ISSUE THREAD

**Issue by MatanTubul** [idan/oauthlib#476]
Hi,

Does this tool support Microsoft accounts like live or Hotmail?
i am trying to authenticate to:

> https://login.microsoftonline.com

**Comment by datatalking** [comment]
No. All Microsoft products use Microsoft code. .net etc.

**Comment by thedrow** [comment]
That's incorrect. It is an OAuth2 API and you can use something like [requests-oauth2](https://github.com/maraujop/requests-oauth2) to authenticate with it.
