### ISSUE TITLE
No module named Flask_OAuthlib

### ISSUE THREAD

**Issue by datatalking** [idan/oauthlib#482]
When I run the oauthlib it generates an error

Traceback (most recent call last):
  File "flaskapp.py", line 4, in <module>
    from Flask_OAuthlib import OAuth
ImportError: No module named Flask_OAuthlib

Should this have been updated to OAuth 1 or 2 or was part of this deprecated?

**Comment by thedrow** [comment]
flask_oauthlib is maintained at https://github.com/lepture/flask-oauthlib. If you have issues about that integration please create them there.
It seems like you haven't installed the library yet. pip install it and you should be fine.
