### ISSUE TITLE
2.0.5 caused "NotImplementedError: Subclasses must implement this method." error

### ISSUE THREAD

**Issue by mc-nathan** [idan/oauthlib#490]
Our commit that failed on Travis is:

https://github.com/masschallenge/impact-api/commit/ccb685f909ebf08d91a2a52249c612bcdb752061

The Travis build with the stack trace is:

https://travis-ci.org/masschallenge/impact-api/builds/289533334

Test passes if we pin oauthlib to 2.0.4.

**Comment by duaneking** [comment]
Confirmed. I get the same issue.

**Comment by lepture** [comment]
Sorry for the release. This is introduced in https://github.com/idan/oauthlib/pull/484

ping @wiliamsouza

could you fix this?

**Comment by wiliamsouza** [comment]
This is an example how to implement `get_authorization_code_scopes` method I do it for django-oauth-toolkit:

```
    def get_authorization_code_scopes(self, client_id, code, redirect_uri, request):
        scopes = []
        fields = {
            "code": code,
        }

        if client_id:
            fields["application__client_id"] = client_id

        if redirect_uri:
            fields["redirect_uri"] = redirect_uri

        grant = Grant.objects.filter(**fields).values()
        if grant.exists():
            grant_dict = dict(grant[0])
            scopes = utils.scope_to_list(grant_dict["scope"])
        return scopes
```

@lepture what fix are you suggesting?

**Comment by lepture** [comment]
@wiliamsouza there are other projects that dependent on this project. We should provide a fallback so that it won't break other's projects.

**Comment by lepture** [comment]
@wiliamsouza oh. I see. It should not be released in 2.x.

**Comment by lepture** [comment]
@mc-nathan could you confirm that https://github.com/idan/oauthlib/tree/2.x works well?

**Comment by lepture** [comment]
ping @duaneking

**Comment by duaneking** [comment]
Thanks @lepture but I'm using flask-oauthlib so I don't have a place to put that method unless I edit flask-oauthlib directly.

**Comment by lepture** [comment]
@duaneking could you use the code in branch 2.x to test if it works?

**Comment by duaneking** [comment]
I'm still relatively new to this level of python debugging so I don't even know how to do that.  My background is actually in C/C++/ObjC/C#/Java/Javascript/Golang and other languages, so I'm still getting ramped up on python in many ways.  We also use AWS for everything so I'm limited by AWS's constraints to deploy to an elastic beanstalk instance I'm using for testing.

How would I do that?

**Comment by lepture** [comment]
@mc-nathan could you confirm that 2.0.6 works?

**Comment by mc-nathan** [comment]
@lepture Confirmed that 2.0.6 works.  Thanks for the quick turn around!
