### ISSUE TITLE
Missing commits and changelog for 2.0.6

### ISSUE THREAD

**Issue by noirbizarre** [idan/oauthlib#492]
2.0.6 version has been published on PyPI but there is no trace of it on github

**Comment by lepture** [comment]
It's here: https://github.com/idan/oauthlib/tree/2.x

There is a mistake when releasing 2.0.5. Master branch is going to be 3.x.

**Comment by lepture** [comment]
BTW, I'm going to creating a new authentication library, which should be a ready to use library with nice API. Flask and Django will be built into the library by default.

https://www.patreon.com/lepture
