### ISSUE TITLE
Missing wheel package on PyPI

### ISSUE THREAD

**Issue by jdufresne** [idan/oauthlib#493]
Universal wheel support was added some time ago:

https://github.com/idan/oauthlib/commit/06c7c58bac102838c46a5bef47e3d1758f7095c0

I noticed that a wheel package is not available on PyPI, only a `.tar.gz` file:

https://pypi.python.org/pypi/oauthlib

To upload the wheel, when you'd normally run `python setup.py sdist upload`, run instead `python setup.py sdist bdist_wheel upload`.

See https://pythonwheels.com/ for additional details. On that page, oauthlib is listed as one of the most used packages with a wheel.

**Comment by lepture** [comment]
It's uploaded by Travis CI.
